### ISSUE TITLE
SBT publish-local is not working

### ISSUE THREAD

**Issue by knightpop** [levkhomich/akka-tracing#86]
I check out from master and run 'sbt publish-local'. but this error occure
`java.lang.NullPointerException
	at scala.collection.mutable.WrappedArray$ofRef.length(WrappedArray.scala:125)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:176)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)
	at scala.collection.generic.GenericTraversableTemplate$$anonfun$flatten$1.apply(GenericTraversableTemplate.scala:146)
	at scala.collection.generic.GenericTraversableTemplate$$anonfun$flatten$1.apply(GenericTraversableTemplate.scala:145)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.GenericTraversableTemplate$class.flatten(GenericTraversableTemplate.scala:145)
	at scala.collection.AbstractTraversable.flatten(Traversable.scala:105)
	at sbt.Defaults$$anonfun$generate$1$$anonfun$apply$8.apply(Defaults.scala:311)
	at sbt.Defaults$$anonfun$generate$1$$anonfun$apply$8.apply(Defaults.scala:311)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (akka-tracing-core/compile:managedSources) java.lang.NullPointerException`

how can i publish-local?

i want to use because of 0.6 support play 2.5

**Comment by knightpop** [comment]
i also delete exist akka-tracing ivy2 cache

**Comment by levkhomich** [comment]
Most likely, you need to install thrift. Also, you can use Maven Central snapshots, latest version is always published there.

**Comment by knightpop** [comment]
@levkhomich Oh I understand! how about make branch about 0.6 snapshot at play-tracing(https://github.com/levkhomich/activator-play-tracing/)? because many use play 2.5.x and they can recognize that soon new version for support play 2.5.x come

**Comment by levkhomich** [comment]
Ok, will try to find some time for it during the weekend.

**Comment by knightpop** [comment]
@levkhomich maybe i can help. I want to use your lib in my service. so I want to study your source. and want to know how to adopt to play 2.5

**Comment by knightpop** [comment]
@levkhomich maybe i can help. I want to use your lib in my service. so I want to study your source. and want to know how to adopt to play 2.5

**Comment by knightpop** [comment]
Oh! already there is PR in activator-play-tracing....

I`ll close this!
